name: Integration-Tests

on:
  push:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master
      - '!main'   # excludes main
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

  # Allows you to run this workflow called from another WF
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    configuration: 'Release'
    solution_path: 'Aranzadi.DocumentAnalysis/Aranzadi.DocumentAnalysis.csproj'
    nuget_feed_name: 'SWF_Burgos_Spain_Artifacts_feed'
    nuget_feed_source: 'https://pkgs.dev.azure.com/TR-Legal-OnlineServices/_packaging/SWF_Burgos_Spain_Artifacts_feed/nuget/v3/index.json'
    password_ado: ${{ secrets.PASSWORD_ADO }}
    nuget_config: './Nuget.Config'

jobs:
  build:

    name: Build and Test
    runs-on: windows-latest

    permissions:
       write-all

    strategy:
      matrix:
        nuget_version: [5.x]
        dotnet_version: [6.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
       dotnet-version: ${{ matrix.dotnet_version }}

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
       nuget-version: ${{ matrix.nuget_version }}

    - name: Auth Nuget TR
      run: dotnet nuget add source ${{ env.nuget_feed_source }} --name ${{ env.nuget_feed_name }} --username 'david.sanchezfuentes@thomsonreuters.com' --password ${{ env.password_ado }} --store-password-in-clear-text --configfile ${{ env.nuget_config }}

    - name: Restore Nuget Packages
      run: dotnet restore ${{ env.solution_path }} --verbosity normal 

    - name: 'Run cp commands'
      id: copyconfig
      run: cp -v ${{github.workspace}}/Settings/appsettings.TEST.test.json ${{github.workspace}}/Settings/appsettings.test.json

    - name: Build Solution
      run: dotnet build ${{ env.solution_path }} --configuration ${{ env.configuration }} --no-restore
    
    - name: DotNet Integration Test DocumentAnalysis
      uses: zyborg/dotnet-tests-report@v1
      if: ${{ !cancelled() }}
      with:
       project_path: ./Aranzadi.DocumentAnalysis.Integration.Test
       report_name: Unit Tests Result
       report_title: Unit Tests Result
       github_token: ${{ secrets.GITHUB_TOKEN }}
       gist_name: unit_tests.md
       gist_badge_label: "Unit-Tests: %Counters_passed%/%Counters_total%"
       set_check_status_from_test_outcome: true